name: Build and Test .NET API

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar la solución
        run: dotnet build --no-restore --configuration Release

      - name: Ejecutar pruebas (si tienes)
        run: dotnet test --no-build --verbosity normal
